export const lightTheme = {
  // shadcn — base claire avec accents bleu cabinet
  '--background': '0.99 0.008 262',
  '--foreground': '0.20 0.04 262',
  '--card': '1 0.006 262',
  '--card-foreground': '0.20 0.04 262',
  '--popover': '1 0.006 262',
  '--popover-foreground': '0.20 0.04 262',
  '--primary': '0.48 0.14 252',
  '--primary-foreground': '0.99 0.01 252',
  '--secondary': '0.96 0.02 262',
  '--secondary-foreground': '0.28 0.05 262',
  '--muted': '0.96 0.015 262',
  '--muted-foreground': '0.50 0.04 262',
  '--accent': '0.94 0.03 262',
  '--accent-foreground': '0.28 0.05 262',
  '--destructive': '0.577 0.245 27.325',
  '--border': '0.90 0.02 262',
  '--input': '0.90 0.02 262',
  '--ring': '0.48 0.14 252',
  // 主要区域
  '--g-main-area-bg': 'oklch(0.97 0.012 262)',
  // 头部
  '--g-header-bg': 'oklch(var(--background))',
  '--g-header-color': 'oklch(var(--foreground))',
  '--g-header-menu-color': 'oklch(var(--accent-foreground))',
  '--g-header-menu-hover-bg': 'oklch(var(--accent))',
  '--g-header-menu-hover-color': 'oklch(var(--accent-foreground))',
  '--g-header-menu-active-bg': 'oklch(var(--primary))',
  '--g-header-menu-active-color': 'oklch(var(--primary-foreground))',
  // 主导航
  '--g-main-sidebar-bg': 'oklch(var(--background))',
  '--g-main-sidebar-menu-color': 'oklch(var(--accent-foreground))',
  '--g-main-sidebar-menu-hover-bg': 'oklch(var(--accent))',
  '--g-main-sidebar-menu-hover-color': 'oklch(var(--accent-foreground))',
  '--g-main-sidebar-menu-active-bg': 'oklch(var(--primary))',
  '--g-main-sidebar-menu-active-color': 'oklch(var(--primary-foreground))',
  // 次导航
  '--g-sub-sidebar-bg': 'oklch(var(--background))',
  '--g-sub-sidebar-menu-color': 'oklch(var(--accent-foreground))',
  '--g-sub-sidebar-menu-hover-bg': 'oklch(var(--accent))',
  '--g-sub-sidebar-menu-hover-color': 'oklch(var(--accent-foreground))',
  '--g-sub-sidebar-menu-active-bg': 'oklch(var(--primary))',
  '--g-sub-sidebar-menu-active-color': 'oklch(var(--primary-foreground))',
  // 标签栏
  '--g-tabbar-bg': 'oklch(var(--background))',
  '--g-tabbar-tab-color': 'oklch(var(--accent-foreground) / 50%)',
  '--g-tabbar-tab-hover-bg': 'oklch(var(--accent) / 50%)',
  '--g-tabbar-tab-hover-color': 'oklch(var(--accent-foreground) / 50%)',
  '--g-tabbar-tab-active-bg': 'oklch(var(--accent))',
  '--g-tabbar-tab-active-color': 'oklch(var(--foreground))',
  // 工具栏
  '--g-toolbar-bg': 'oklch(var(--background))',
} as const

/** Mode sombre — bleu nuit élégant (cabinet juridique) */
export const darkTheme = {
  // shadcn
  '--background': '0.17 0.045 262',
  '--foreground': '0.94 0.02 262',
  '--card': '0.21 0.05 262',
  '--card-foreground': '0.94 0.02 262',
  '--popover': '0.22 0.052 262',
  '--popover-foreground': '0.94 0.02 262',
  '--primary': '0.62 0.15 250',
  '--primary-foreground': '0.99 0.01 250',
  '--secondary': '0.26 0.05 262',
  '--secondary-foreground': '0.92 0.02 262',
  '--muted': '0.24 0.048 262',
  '--muted-foreground': '0.70 0.04 262',
  '--accent': '0.30 0.075 255',
  '--accent-foreground': '0.96 0.02 262',
  '--destructive': '0.65 0.19 22',
  '--border': '0.32 0.055 262',
  '--input': '0.28 0.05 262',
  '--ring': '0.62 0.15 250',
  // 主要区域 — fond légèrement plus profond que les cartes
  '--g-main-area-bg': 'oklch(0.14 0.042 260)',
  // 头部
  '--g-header-bg': 'oklch(0.13 0.048 258)',
  '--g-header-color': 'oklch(var(--foreground))',
  '--g-header-menu-color': 'oklch(var(--muted-foreground))',
  '--g-header-menu-hover-bg': 'oklch(var(--muted))',
  '--g-header-menu-hover-color': 'oklch(var(--foreground))',
  '--g-header-menu-active-bg': 'oklch(var(--primary) / 90%)',
  '--g-header-menu-active-color': 'oklch(var(--primary-foreground))',
  // 主导航 — barre latérale plus sombre
  '--g-main-sidebar-bg': 'oklch(0.12 0.05 258)',
  '--g-main-sidebar-menu-color': 'oklch(var(--muted-foreground))',
  '--g-main-sidebar-menu-hover-bg': 'oklch(0.22 0.055 262)',
  '--g-main-sidebar-menu-hover-color': 'oklch(var(--foreground))',
  '--g-main-sidebar-menu-active-bg': 'oklch(var(--primary) / 88%)',
  '--g-main-sidebar-menu-active-color': 'oklch(var(--primary-foreground))',
  // 次导航
  '--g-sub-sidebar-bg': 'oklch(0.15 0.046 260)',
  '--g-sub-sidebar-menu-color': 'oklch(var(--muted-foreground))',
  '--g-sub-sidebar-menu-hover-bg': 'oklch(var(--muted))',
  '--g-sub-sidebar-menu-hover-color': 'oklch(var(--foreground))',
  '--g-sub-sidebar-menu-active-bg': 'oklch(var(--primary) / 85%)',
  '--g-sub-sidebar-menu-active-color': 'oklch(var(--primary-foreground))',
  // 标签栏
  '--g-tabbar-bg': 'oklch(0.13 0.048 258)',
  '--g-tabbar-tab-color': 'oklch(var(--muted-foreground))',
  '--g-tabbar-tab-hover-bg': 'oklch(var(--muted) / 60%)',
  '--g-tabbar-tab-hover-color': 'oklch(var(--foreground) / 80%)',
  '--g-tabbar-tab-active-bg': 'oklch(var(--accent))',
  '--g-tabbar-tab-active-color': 'oklch(var(--foreground))',
  // 工具栏
  '--g-toolbar-bg': 'oklch(0.13 0.048 258)',
} as const
